### ISSUE TITLE
Error: image kiwenlau/serf-dnsmasq not found

### ISSUE THREAD

**Issue by sunyifei83** [kiwenlau/hadoop-cluster-docker#1]
#sudo docker pull index.alauda.cn/kiwenlau/serf-dnsmasq   

but,
--------
Pulling repository index.alauda.cn/kiwenlau/serf-dnsmasq
2015/06/09 05:29:32 Error: image kiwenlau/serf-dnsmasq not found

**Comment by kiwenlau** [comment]
please add tag "0.1.0" when you pull the image
docker will pull "latest" image by default
sudo docker pull index.alauda.cn/kiwenlau/serf-dnsmasq:0.1.0

or you can pull the image from DockerHub
sudo docker pull kiwenlau/serf-dnsmasq:0.1.0

## Thanks!

**Comment by sunyifei83** [comment]
sudo docker pull index.alauda.cn/kiwenlau/serf-dnsmasq:0.1.0   无效，之前就试过了

经过测试   英文页面所留地址可用
sudo docker pull kiwenlau/serf-dnsmasq:0.1.0

**Comment by kiwenlau** [comment]
我在东京两个都可以拉取啊！不清楚是什么原因了:(

我再check一下吧

谢谢！

**Comment by sunyifei83** [comment]
非常感谢，实例运行正常。

**Comment by kiwenlau** [comment]
如果可以的话，帮忙在多台机器上测试以下第一个链接:)
