### ISSUE TITLE
about hadoop compile

### ISSUE THREAD

**Issue by yanshuicc** [kiwenlau/hadoop-cluster-docker#10]
i have see your install hadoop cmd in hadoop-base dockerfile, it's just a ln cmd instead of install cmd
(/ □ \\):
   RUN ln -s /usr/local/hadoop-2.3.0 /usr/local/hadoop.

you must have compiled hadoop and i found compile step in your blog. http://www.cnblogs.com/kiwenlau/p/4227204.html

maybe need  a ADD cmd in dockerfile.
ADD xxx /usr/local/hadoop-2.3.0

**Comment by kiwenlau** [comment]
Thank you for your remind!
Probably, I will update this project within 1 month for more optimizations and fix this problem:)
