### ISSUE TITLE
changing the base images to centOS

### ISSUE THREAD

**Issue by TaylorNm08z** [kiwenlau/hadoop-cluster-docker#11]
Hii 

I'm keen in building centos how can i reference your and build a centos rather then ubuntu

**Comment by kiwenlau** [comment]
Centos is quite different with ubuntu. And you need to compile hadoop by your self.

**Comment by TaylorNm08z** [comment]
I see .. how I could go about doing so as i super keen in toward that ? :)

**Comment by kiwenlau** [comment]
Follow the steps:
1. Compile Hadoop on CentOS by your self.
Download corresponding source code.[http://hadoop.apache.org/releases.html]( http://hadoop.apache.org/releases.html)
In the source code directory, you can find "BUILDING.txt", whill will tell you how to compile hadoop.

2. Install Hadoop on CentOS, develop corresponding Docker images. Note that it is not as simple as just change the base image. Find blogs about how to install all components on centos.

Good Luck!

**Comment by TaylorNm08z** [comment]
Noted ...just wondering if there a possible to way to hide/disable the following detail display during the ssh slave1kiwenlau.com . In short rather then display this 

Warning: Permanently added 'slave2.kiwenlau.com,172.17.0.67' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 15.04 (GNU/Linux 3.13.0-53-generic x86_64)
 * Documentation:  https://help.ubuntu.com/
The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

can just go directly go in here "root@slave2:~#"

**Comment by TaylorNm08z** [comment]
Hii Mr Kiwen 

I had did research on main reason why enterprise are using ubuntu to develop the hadoop cluster into a container check this articles out  . Thanks ! Have a Great Day Cheers ! :+1: 
[WP_Hadoop_WEB.pdf](https://github.com/kiwenlau/hadoop-cluster-docker/files/238471/WP_Hadoop_WEB.pdf)
