### ISSUE TITLE
slaves cannot be found 

### ISSUE THREAD

**Issue by TaylorNm08z** [kiwenlau/hadoop-cluster-docker#12]
I had type the following : 
root@master:~# : serf member
master.kiwenlau.com  172.17.0.65:7946  alive  

5 mins later still 

master.kiwenlau.com  172.17.0.65:7946  alive  

don't seem to load up

**Comment by kiwenlau** [comment]
Did you solve the problem?

**Comment by TaylorNm08z** [comment]
Yup I docker run the container can work le ! I got another issue please guide me on another issue !
