### ISSUE TITLE
Hadoop-cluster-Docker Inquires

### ISSUE THREAD

**Issue by TaylorNm08z** [kiwenlau/hadoop-cluster-docker#15]
Hi

I'm confuse on what are the file inside the docker image before get clone how I could take a look at it . Looking forward to heard from you soon ! can guide me how you build your dockerfile images ? I very confuse

**Comment by kiwenlau** [comment]
用中文聊吧，然后，请具体问题讲清楚...

**Comment by TaylorNm08z** [comment]
I don't really understand chinese don't mind in english ?

**Comment by TaylorNm08z** [comment]
Hi Mr Kiwenlau,

the following are my question I would like ask : 

1. I'm confuse on what are the file inside the docker image before get get clone from the GitHub ?
2. how you build your hadoop-cluster-docker I very curious to learn that ! Would you mind teach me   how you build those ?

**Comment by kiwenlau** [comment]
Sorry for the late reply.
1. I can not understand the first problem.
2. Build image using "docker build" command and push image to DockerHub using "docker push" command:

You can check following file for building all docker images:
**https://github.com/kiwenlau/hadoop-cluster-docker/blob/master/build-image.sh**

**Comment by TaylorNm08z** [comment]
Hi Mr Kiwenlau,

1. What I am trying to ask is,  Do you mind indicate a step by step guide on how you create the 
    docker images ? At least i have a draft idea on how you create  your docker images file maybe 1
    example? 


2.

**Comment by kiwenlau** [comment]
To build a docker image:
1. Write Dockerfile
2. Run "docker build command"

[](https://docs.docker.com/engine/reference/builder/)

**Comment by TaylorNm08z** [comment]
Before you push your dockerfile into the docker hub.  Inside your dockerfile i container what ?

why we stiill need to get the source code from GitHub?

**Comment by kiwenlau** [comment]
You can just pull all required images by running "docker pull".And you don't have to build image by your self. In this case, you don't need Dockerfile.
However, to run the project, you need to get the shell script "start-container.sh".

**Comment by TaylorNm08z** [comment]
Don't need Dockerfile  ? 

we still sudo docker pull kiwenlau/hadoop-master:0.1.0?

**Comment by TaylorNm08z** [comment]
Let say I would like you build my own docker image. Don't mind at least tell how you go about process one of the image here therefore I have a better understanding !

**Comment by kiwenlau** [comment]
You can check following file for building all docker images:
https://github.com/kiwenlau/hadoop-cluster-docker/blob/master/build-image.sh

**Comment by TaylorNm08z** [comment]
Just would like to clear my confusion since we no need to build our own docker images why we still need  sudo docker pull kiwenlau/hadoop-master:0.1.0?

**Comment by kiwenlau** [comment]
Using following command to build hadoop-base image:

```
cd hadoop-cluster-docker/hadoop-base
sudo docker build -t kiwenlau/hadoop-base:0.1.0 .
```

**Comment by TaylorNm08z** [comment]
what is the purpose of sudo docker pull kiwenlau/hadoop-master:0.1.0?

**Comment by kiwenlau** [comment]
The purpose of "sudo docker pull kiwenlau/hadoop-master:0.1.0" is to download docker image.

**You should spend more time on studying Docker**

I can not explain ever details...

**Comment by TaylorNm08z** [comment]
Thank ! I re-read through and have full understand !!! you are an awesome developer  5 start for you !!!! :+1:  :+1: :+1: :+1: :+1: :+1:

**Comment by ambodi** [comment]
@kiwenlau  @TaylorNm08z you don't need any sudo. You can just pull. Even for building on your machine, you don't need sudo. It's because Docker demon runs as a root user. Read more here: https://docs.docker.com/engine/installation/linux/ubuntulinux/

**Comment by kiwenlau** [comment]
You need sudo to run docker command when you are not root user.
