### ISSUE TITLE
pengding in wordcount.sh

### ISSUE THREAD

**Issue by superlbr** [kiwenlau/hadoop-cluster-docker#25]
![image](https://cloud.githubusercontent.com/assets/8142164/17459720/6a68b98a-5c77-11e6-83fb-0a22c7580648.png)

**Comment by superlbr** [comment]
it got stuck.
![image](https://cloud.githubusercontent.com/assets/8142164/17459724/84df515c-5c77-11e6-8a80-9bf38e075475.png)

**Comment by superlbr** [comment]
1/1 local-dirs are bad: /tmp/hadoop-root/nm-local-dir; 
1/1 log-dirs are bad: /usr/local/hadoop/logs/userlogs

**Comment by superlbr** [comment]
经测试，这个是docker储存空间不足。

**Comment by superlbr** [comment]
![image](https://cloud.githubusercontent.com/assets/8142164/17460393/24d54d96-5c97-11e6-8a51-04d3333734fa.png)
新错误，不清楚原因

**Comment by superlbr** [comment]
![image](https://cloud.githubusercontent.com/assets/8142164/17460407/c0038ad0-5c97-11e6-93f0-d5f9193b1730.png)
真心累呀

**Comment by kiwenlau** [comment]
大概是内存不够吧

**Comment by superlbr** [comment]
内存要多少算够

**Comment by superlbr** [comment]
果然，docker内存设为4GB，ok

**Comment by superlbr** [comment]
![image](https://cloud.githubusercontent.com/assets/8142164/17461434/d5cb9822-5cbe-11e6-9521-2e64134af1c6.png)

**Comment by GuaiLong618** [comment]
> ![image](https://cloud.githubusercontent.com/assets/8142164/17460407/c0038ad0-5c97-11e6-93f0-d5f9193b1730.png)
> 真心累呀

wordcount output:
cat: `output/part-r-00000': No such file or directory
这个问题是怎么解决的? 
我也遇到这个问题
