### ISSUE TITLE
slaves cannot be found

### ISSUE THREAD

**Issue by Kejia** [kiwenlau/hadoop-cluster-docker#3]
on osx, a master cannot find its default 2 slaves: slave1.kiwenlau.com and slave2.kiwenlau.com. the 2 urls must be added to /etc/hosts:
172.17.0.2      slave1.kiwenlau.com slave1

**Comment by kiwenlau** [comment]
Hi Kejia,

We cannot change /etc/hosts file in Docker container. So I use serf/dnsmasq for DNS service, however, it will take some time for serf/dnsmasq to set up DNS service after starting containers.

Best regards,
Kiwenlau

**Comment by TaylorNm08z** [comment]
I have the issue how what i should do now? 

I type gedit /serf/dnsmasq ?
