### ISSUE TITLE
Comments and a doubt about Docker volume and HDFS

### ISSUE THREAD

**Issue by GustavoRPS** [kiwenlau/hadoop-cluster-docker#4]
I've searched many articles about Hadoop running on Docker and like Mathew said "this is a unique one," indeed the strategy adopted is very good to make a set of big data of low cost and low complexity.

Thank you very much for sharing this!

But I stayed with a doubt ... Is there any problem in using the feature `docker volume`  to "share" folder `hdfs` of the `hadoop-master` with the `host` in order to insert new files and make backups.

Such doubts came up to me after reading this article [Understanding Volumes in Docker by Adrian Mouat] (http://container-solutions.com/understanding-volumes-docker/)

**Comment by kiwenlau** [comment]
I think it is OK to share hdfs folder of hadoo-master with the host. And you can try by yourself. Thanks.
