### ISSUE TITLE
Problems to connect on master when run "./run-wordcount.sh" on master

### ISSUE THREAD

**Issue by GustavoRPS** [kiwenlau/hadoop-cluster-docker#5]
All steps were successful but when I try to run the `./run-wordcount.sh` on `master` I receive the following messages:
```
15/09/18 15:34:14 INFO client.RMProxy: Connecting to ResourceManager at master.kiwenlau.com/172.17.0.8:8040
15/09/18 15:34:16 INFO ipc.Client: Retrying connect to server: master.kiwenlau.com/172.17.0.8:8040. Already tried 0 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
...
15/09/18 15:39:53 INFO ipc.Client: Retrying connect to server: master.kiwenlau.com/172.17.0.8:8040. Already tried 9 time(s); retry policy is RetryUpToMaximumCountWithFixedSleep(maxRetries=10, sleepTime=1000 MILLISECONDS)
```

Then I send `SIGINT` signal  and I receive the following messages:
```
input file1.txt:
Hello Hadoop

input file2.txt:
Hello Docker

wordcount output:
cat: `output/part-r-00000': No such file or directory
```

## Logs
- [root@master:~# cat /root/serf_log](https://gist.github.com/GustavoRPS/fd6a2f2802f272b28baf#file-master-root-serf_log)
- [root@slave1:~# cat /root/serf_log](https://gist.github.com/GustavoRPS/fd6a2f2802f272b28baf#file-slave1-root-serf_log)

There are other ways of logs that can help you know what's going on? I could not use the YARN.

**Comment by kiwenlau** [comment]
Hi,
Have you solved this problem?

You need to wait for about 1 minutes to run start-hadoop.sh for the setting up of serf and dnsmasq service...
