### ISSUE TITLE
serf cluster 新加入(非第一台机器)的机器是否都需要指定JOIN_IP

### ISSUE THREAD

**Issue by quickj** [kiwenlau/hadoop-cluster-docker#6]
@kiwenlau 你好。我看slave hadoop启动的时候都需要配置 -e JOIN_IP=$FIRST_IP 如下:
sudo docker run -d -t --dns 127.0.0.1 -P --name slave$i -h slave$i.kiwenlau.com -e JOIN_IP=$FIRST_IP kiwenlau/hadoop-slave:0.1.0 &> /dev/null
serf是否都需要配置这个环境变量才能工作，那么FIRT_IP的机器是否每次都要先启动。

**Comment by kiwenlau** [comment]
JOIN_IP是serf所需要的环境变量。
[hadoop-cluster-docker/serf-dnsmasq/serf/start-serf-agent.sh](https://github.com/kiwenlau/hadoop-cluster-docker/blob/c466d85ef4bb3a240d46ce55ff0a3cfca3343731/serf-dnsmasq/serf/start-serf-agent.sh)

Master需要首先启动！然后通过FIRT_IP告诉Slave它的IP。Slave上的serf agent才能与master上的serf agent进行通信... 请参考为的博客[基于Docker快速搭建多节点Hadoop集群](http://www.dockone.io/article/395):

容器启动时，master节点的IP会传给所有slave节点。serf会在container启动后立即启动。slave节点上的serf agent会马上发现master节点（master IP它们都知道嘛），master节点就马上发现了所有slave节点。然后它们之间通过互相交换信息，所有节点就能知道其他所有节点的存在了。（Everyone will know Everyone）。serf发现新的节点时，就会重新配置dnsmasq，然后重启dnsmasq。所以dnsmasq就能够解析集群的所有节点的域名啦。这个过程随着节点的增加会耗时更久，因此，若配置的Hadoop节点比较多，则在启动容器后需要测试serf是否发现了所有节点，DNS是否能够解析所有节点域名。稍等片刻才能启动Hadoop。这个解决方案是由SequenceIQ公司提出的，该公司专注于将Hadoop运行在Docker中。参考这个[演讲稿](http://www.slideshare.net/JanosMatyas/docker-based-hadoop-provisioning)。

谢谢！

**Comment by quickj** [comment]
Thanks for your perfect reply.

**Comment by kiwenlau** [comment]
Nothing~
