### ISSUE TITLE
can't upload By Java.

### ISSUE THREAD

**Issue by QingHui653** [kiwenlau/hadoop-cluster-docker#62]
我开启了 9000 和 8032 端口. 使用 JAVA API 进行 上传文件. 会提示 : `could only be replicated to 0 nodes instead of minReplication (=1).  There are 2 datanode(s) running and 2 node(s) are excluded in this operation. `

我不明白这是 hadoop 配置问题还是什么? 目前 还出现在 sequenceiq/hadoop-docker. 自己搭建 的 hadoop 2.9.1 也存在 此问题. 

Thank you.

**Comment by chenbaochao** [comment]
> 我开启了 9000 和 8032 端口. 使用 JAVA API 进行 上传文件. 会提示 : could only be replicated to 0 nodes instead of minReplication (=1).  There are 2 datanode(s) running and 2 node(s) are excluded in this operation. 
> 我不明白这是 hadoop 配置问题还是什么? 目前 还出现在 sequenceiq/hadoop-docker. 自己搭建 的 hadoop 2.9.1 也存在 此问题.
> Thank you.

**Comment by chenbaochao** [comment]
在吗？ 我也出现了这个问题.如果找到问题了 麻烦告诉下 。 谢谢了
