### ISSUE TITLE
serf members

### ISSUE THREAD

**Issue by sunjingwu** [kiwenlau/hadoop-cluster-docker#9]
root@master:~# serf members
Error connecting to Serf agent: dial tcp 127.0.0.1:7373: connection refused

./start-ssh-serf.sh: line 9: /etc/serf/start-serf-agent.sh: Permission denied

**Comment by qiangweizhang** [comment]
楼猪，已经完全搭建成功 只是还不知道在这个端口是这么映射的 想使用eclipse 开发程序 不晓得hdfs的怎么配置呢

**Comment by qiangweizhang** [comment]
Dockerfile 中的端口怎么不能使用呢

**Comment by kiwenlau** [comment]
Which port?

**Comment by qiangweizhang** [comment]
已经搞定

**Comment by kiwenlau** [comment]
@sunjingwu Have you solved your problem? Sorry for the late response.
